ALTER TABLE machines 
ADD COLUMN min_capacity VARCHAR(50) DEFAULT '0',
ADD COLUMN max_capacity VARCHAR(50) DEFAULT '0',
ADD COLUMN unit VARCHAR(20) DEFAULT 'KG/HR',
ADD COLUMN description TEXT,
ADD COLUMN image VARCHAR(255) DEFAULT NULL;
